name: Snyk Java Workflow
on: push

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'  # Adjust if needed

      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven

      - name: Run Snyk Code & Dependency Scan
        uses: snyk/actions/node@master
        continue-on-error: true  # Required to allow SARIF upload step to run
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --all-projects --sarif-file-output=snyk.sarif

      - name: Upload SARIF to GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
